#!/bin/sh
as10="as10r1 as10r2 as10r3 as10r4"
as20="as20r1"
as30="as30r1"
as40="as40r1"
all="$as10 $as20 $as30 $as40"

update_router () { 
   	echo "MAJ de $1"
   	mkdir -p conf/$1/
	sshpass -p 'root' scp -o StrictHostKeyChecking=no conf/$1/* root@$1:/etc/quagga/
	sshpass -p 'root' ssh -o StrictHostKeyChecking=no root@$1 '/etc/init.d/S27quagga restart'
}


case $1 in
	"as10")
	for elem in $as10 
	do
		update_router $elem &
	done
    ;;
    "as20")
	for elem in $as20 
	do
		update_router $elem &
	done
    ;;
    "as30")
	for elem in $as30
	do
		update_router $elem &
	done
    ;;
    "as40")
	for elem in $as40
	do
		update_router $elem &
	done
    ;;
    "all")
	for elem in $all 
	do
		update_router $elem &
	done
    ;;
  	*)
	update_router $1
esac
